### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kmiyashiro** [cowboyd/eslint-plugin-prefer-let#1]
Can you please create a new release for the errant console.log removal?

**Comment by kmiyashiro** [comment]
@cowboyd *gentle ping*

**Comment by cowboyd** [comment]
👍 https://www.npmjs.com/package/eslint-plugin-prefer-let

**Comment by haltcase** [comment]
Holy crap I was wondering where that log was coming from. Thanks for this :rofl: Also happy to see a 1.0.0

**Comment by kmiyashiro** [comment]
🙇🏻
