### ISSUE TITLE
3.0 ChangeLog

### ISSUE THREAD

**Issue by ai** [cowboyd/eslint-plugin-prefer-let#10]
I see 3.0 release in npm, but can’t find it here https://www.npmjs.com/package/eslint-plugin-prefer-let/v/3.0.0

**Comment by cowboyd** [comment]
@ai Sorry about that! This plugin's new home is [https://github.com/thefrontside/javascript/tree/v2/packages/eslint-plugin-prefer-let](https://github.com/thefrontside/javascript/tree/v2/packages/eslint-plugin-prefer-let)

I'll go ahead and archive this repository. Let me know if you have any other questions!
